### ISSUE TITLE
Incompatibility with stale teensy_loader_cli versions

### ISSUE THREAD

**Issue by ticky** [bobbin-rs/bobbin-cli#1]
Hi there,

Bobbin expects teensy_loader_cli’s command-line signature to have the same format as version 2.1 does (mcu passed as `--mcu`) whilst some versions marked as “2.1” instead accept `-mmcu`, and thus aren’t detected by bobbin.

Version 2.1 as shipped by Homebrew is one such version. I’ve opened an issue (homebrew/homebrew-core#17087) to get the version in Homebrew updated to the “newer” 2.1, but it may be useful for bobbin to provide compatibility with the prior version, the source to which remains hosted on pjrc’s site at <https://www.pjrc.com/teensy/teensy_loader_cli.2.1.zip>.

**Comment by jcsoo** [comment]
In ed8e6ef I've updated bobbin-cli to use -mmcu instead of --mcu. It's possible that someone is running a version of teensy_loader_cli that only supports --mcu but there's no easy way to detect this. -mmcu is likely to work for most of the installed base.

This works successfully with the version of teensy_loader_cli that I just installed from Homebrew, which looks like it includes your pull request. I haven't had a chance to build the older 2.1, but if you have the binary available, let me know if it works for that version.
